---
galaxy_info:
  role_name: "keepalived"
  author: "Svyatoslav"
  description: "Ansible Role for keepalived installation"
  company: ""
  license: "Apache"
  min_ansible_version: "2.8"
  issue_tracker_url: "http://localhost"
  platforms:
    - name: "Ubuntu"
      versions:
        - "bionic"
  galaxy_tags: []
dependencies: []
